/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CaregiverDashboardRouteImport } from './routes/caregiver-dashboard'
import { Route as CaregiversRouteImport } from './routes/caregivers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ForCaregiversRouteImport } from './routes/for-caregivers'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as CaregiversIndexRouteImport } from './routes/caregivers.index'
import { Route as CaregiversCaregiverIdRouteImport } from './routes/caregivers.$caregiverId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverDashboardRoute = CaregiverDashboardRouteImport.update({
  id: '/caregiver-dashboard',
  path: '/caregiver-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiversRoute = CaregiversRouteImport.update({
  id: '/caregivers',
  path: '/caregivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCaregiversRoute = ForCaregiversRouteImport.update({
  id: '/for-caregivers',
  path: '/for-caregivers',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BookingsRoute,
} as any)
const CaregiversIndexRoute = CaregiversIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaregiversRoute,
} as any)
const CaregiversCaregiverIdRoute = CaregiversCaregiverIdRouteImport.update({
  id: '/$caregiverId',
  path: '/$caregiverId',
  getParentRoute: () => CaregiversRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/caregiver-dashboard': typeof CaregiverDashboardRoute
  '/caregivers': typeof CaregiversRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/for-caregivers': typeof ForCaregiversRoute
  '/help': typeof HelpRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/bookings/new': typeof BookingsNewRoute
  '/caregivers/$caregiverId': typeof CaregiversCaregiverIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/caregivers/': typeof CaregiversIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/caregiver-dashboard': typeof CaregiverDashboardRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/for-caregivers': typeof ForCaregiversRoute
  '/help': typeof HelpRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/bookings/new': typeof BookingsNewRoute
  '/caregivers/$caregiverId': typeof CaregiversCaregiverIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/caregivers': typeof CaregiversIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/caregiver-dashboard': typeof CaregiverDashboardRoute
  '/caregivers': typeof CaregiversRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/for-caregivers': typeof ForCaregiversRoute
  '/help': typeof HelpRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/bookings/new': typeof BookingsNewRoute
  '/caregivers/$caregiverId': typeof CaregiversCaregiverIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/caregivers/': typeof CaregiversIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/caregiver-dashboard'
    | '/caregivers'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/for-caregivers'
    | '/help'
    | '/messages'
    | '/privacy'
    | '/safety'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/bookings/new'
    | '/caregivers/$caregiverId'
    | '/bookings/'
    | '/caregivers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/caregiver-dashboard'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/for-caregivers'
    | '/help'
    | '/messages'
    | '/privacy'
    | '/safety'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/bookings/new'
    | '/caregivers/$caregiverId'
    | '/bookings'
    | '/caregivers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/caregiver-dashboard'
    | '/caregivers'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/for-caregivers'
    | '/help'
    | '/messages'
    | '/privacy'
    | '/safety'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/bookings/new'
    | '/caregivers/$caregiverId'
    | '/bookings/'
    | '/caregivers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  CaregiverDashboardRoute: typeof CaregiverDashboardRoute
  CaregiversRoute: typeof CaregiversRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  ForCaregiversRoute: typeof ForCaregiversRoute
  HelpRoute: typeof HelpRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver-dashboard': {
      id: '/caregiver-dashboard'
      path: '/caregiver-dashboard'
      fullPath: '/caregiver-dashboard'
      preLoaderRoute: typeof CaregiverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregivers': {
      id: '/caregivers'
      path: '/caregivers'
      fullPath: '/caregivers'
      preLoaderRoute: typeof CaregiversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-caregivers': {
      id: '/for-caregivers'
      path: '/for-caregivers'
      fullPath: '/for-caregivers'
      preLoaderRoute: typeof ForCaregiversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/caregivers/': {
      id: '/caregivers/'
      path: '/'
      fullPath: '/caregivers/'
      preLoaderRoute: typeof CaregiversIndexRouteImport
      parentRoute: typeof CaregiversRoute
    }
    '/caregivers/$caregiverId': {
      id: '/caregivers/$caregiverId'
      path: '/$caregiverId'
      fullPath: '/caregivers/$caregiverId'
      preLoaderRoute: typeof CaregiversCaregiverIdRouteImport
      parentRoute: typeof CaregiversRoute
    }
  }
}

interface BookingsRouteChildren {
  BookingsNewRoute: typeof BookingsNewRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsNewRoute: BookingsNewRoute,
  BookingsIndexRoute: BookingsIndexRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface CaregiversRouteChildren {
  CaregiversCaregiverIdRoute: typeof CaregiversCaregiverIdRoute
  CaregiversIndexRoute: typeof CaregiversIndexRoute
}

const CaregiversRouteChildren: CaregiversRouteChildren = {
  CaregiversCaregiverIdRoute: CaregiversCaregiverIdRoute,
  CaregiversIndexRoute: CaregiversIndexRoute,
}

const CaregiversRouteWithChildren = CaregiversRoute._addFileChildren(
  CaregiversRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRouteWithChildren,
  CaregiverDashboardRoute: CaregiverDashboardRoute,
  CaregiversRoute: CaregiversRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  ForCaregiversRoute: ForCaregiversRoute,
  HelpRoute: HelpRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
