/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CaregiversRouteImport } from './routes/caregivers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as CaregiversCaregiverIdRouteImport } from './routes/caregivers.$caregiverId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiversRoute = CaregiversRouteImport.update({
  id: '/caregivers',
  path: '/caregivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BookingsRoute,
} as any)
const CaregiversCaregiverIdRoute = CaregiversCaregiverIdRouteImport.update({
  id: '/$caregiverId',
  path: '/$caregiverId',
  getParentRoute: () => CaregiversRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/caregivers': typeof CaregiversRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/bookings/new': typeof BookingsNewRoute
  '/caregivers/$caregiverId': typeof CaregiversCaregiverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/caregivers': typeof CaregiversRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/bookings/new': typeof BookingsNewRoute
  '/caregivers/$caregiverId': typeof CaregiversCaregiverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/caregivers': typeof CaregiversRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/bookings/new': typeof BookingsNewRoute
  '/caregivers/$caregiverId': typeof CaregiversCaregiverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/caregivers'
    | '/dashboard'
    | '/discover'
    | '/messages'
    | '/safety'
    | '/settings'
    | '/signup'
    | '/bookings/new'
    | '/caregivers/$caregiverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/caregivers'
    | '/dashboard'
    | '/discover'
    | '/messages'
    | '/safety'
    | '/settings'
    | '/signup'
    | '/bookings/new'
    | '/caregivers/$caregiverId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookings'
    | '/caregivers'
    | '/dashboard'
    | '/discover'
    | '/messages'
    | '/safety'
    | '/settings'
    | '/signup'
    | '/bookings/new'
    | '/caregivers/$caregiverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  CaregiversRoute: typeof CaregiversRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  MessagesRoute: typeof MessagesRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregivers': {
      id: '/caregivers'
      path: '/caregivers'
      fullPath: '/caregivers'
      preLoaderRoute: typeof CaregiversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/caregivers/$caregiverId': {
      id: '/caregivers/$caregiverId'
      path: '/$caregiverId'
      fullPath: '/caregivers/$caregiverId'
      preLoaderRoute: typeof CaregiversCaregiverIdRouteImport
      parentRoute: typeof CaregiversRoute
    }
  }
}

interface BookingsRouteChildren {
  BookingsNewRoute: typeof BookingsNewRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsNewRoute: BookingsNewRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface CaregiversRouteChildren {
  CaregiversCaregiverIdRoute: typeof CaregiversCaregiverIdRoute
}

const CaregiversRouteChildren: CaregiversRouteChildren = {
  CaregiversCaregiverIdRoute: CaregiversCaregiverIdRoute,
}

const CaregiversRouteWithChildren = CaregiversRoute._addFileChildren(
  CaregiversRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRouteWithChildren,
  CaregiversRoute: CaregiversRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  MessagesRoute: MessagesRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
